# WEB PROPERTIES
server:
  port: 8082
  
# DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydb?useSSL=false
    username: omar
    password: root
#    url: jdbc:oracle:thin:@//10.63.32.192:1521/SWBDPROD?useSSL=false
#    username: ADQUIRENTE
#    password: ADQUIRENTE

# JPA (JpaBaseConfiguration, HibernateJpaAutoConfiguration)
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
#        dialect: org.hibernate.dialect.Oracle10gDialect
